Repository sendgrid/sendgrid-csharp, pull requests merged in 2018-10, with the labels that each got.

#751 Update to remove compiler warnings based on stylecop/xunit
  src/SendGrid/Helpers/Mail/SendGridMessage.cs
  src/SendGrid/SendGridClient.cs
  tests/SendGrid.Tests/Helpers/Mail/SendGridMessageTests.cs
  tests/SendGrid.Tests/Integration.cs
  tests/SendGrid.Tests/Reliability/RetryDelegatingHandlerTests.cs
Labels: difficulty: medium, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#754 Removed references to Microsoft.AspNetCore.Http.Abstractions package …
  src/SendGrid/SendGrid.csproj
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: community enhancement

#794 Updated broken links to examples
  CONTRIBUTING.md
Labels: difficulty: easy, good first issue, hacktoberfest, status: hacktoberfest approved, status: ready for deploy

#791 fixed typo in mail example
  examples/mail/mail.cs
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy

#790 Change the environment variable placeholders to be consistent amongst…
  ExampleCoreProject/Example.cs
  ExampleNet45Project/Example.cs
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy

#767 Directly link online version of CLA and fix email mentions
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: work in progress, type: docs update

#762 TROUBLESHOOTING.md broken link fix
  TROUBLESHOOTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: bug

#783 Update documentation with new Git workflow
  .github/PULL_REQUEST_TEMPLATE
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update

#814 Modification in Prerequisites for installation
  README.md
Labels: difficulty: easy, hacktoberfest, status: hacktoberfest approved, status: ready for deploy, type: docs update
