Repository sendgrid/sendgrid-csharp, pull requests merged in 2018-08, with the labels that each got.

#718 update readme tags
  README.md
Labels: difficulty: easy, status: code review request, type: docs update

#720 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: status: ready for deploy, type: docs update

#586 Allow for duplicate keys in QueryParams
  src/SendGrid/SendGridClient.cs
Labels: difficulty: medium, hacktoberfest, status: code review request, type: bug

#601 .Net 4.5 References
  nuspec/Sendgrid.9.9.0.nuspec
  src/SendGrid/SendGrid.csproj
Labels: difficulty: easy, hacktoberfest, status: code review request, type: community enhancement

#610 Added test to check the license date
  tests/SendGrid.Tests/LicenseTests.cs
Labels: difficulty: medium, hacktoberfest, status: code review request, type: sendgrid enhancement

#613 update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: docs update

#615 Fixed typo in Usage.md
  USAGE.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: docs update

#617 added codecov support
  .travis.yml
Labels: difficulty: easy, hacktoberfest, status: code review request, type: sendgrid enhancement

#618 Added links to code base in CONTRIBUTION.md
  CONTRIBUTING.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: docs update

#627 Add Code Review to Contributing.md
  CONTRIBUTING.md
  README.md
Labels: difficulty: easy, hacktoberfest, status: code review request, type: docs update

#643 HTML to Plain text documentation
  USE_CASES.md
Labels: difficulty: medium, status: code review request, type: sendgrid enhancement

#688 Fix mixup of Response.Body and Response.Header summaries
  src/SendGrid/Response.cs
Labels: difficulty: easy, status: ready for deploy, type: sendgrid enhancement

#700 #638 Add default value for SubstitutionTag parameter
  src/SendGrid/Helpers/Mail/SendGridMessage.cs
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement

#702 Fixed virtual bug
  src/SendGrid/SendGridClient.cs
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement

#719 Update travis config to use relative path
  .travis.yml
Labels: difficulty: easy, status: code review request, type: sendgrid enhancement
