Repository sendgrid/sendgrid-csharp, pull requests merged in 2020-08, with the labels that each got.

#812 feat: Add dockerized event webhook consumer example
  examples/eventwebhook/consumer/Dockerfile
  examples/eventwebhook/consumer/README.md
  examples/eventwebhook/consumer/SendGridEventWebhookConsumer.sln
  examples/eventwebhook/consumer/Src/EventWebhook/Controllers/EventWebhookController.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Converters/CategoryConverter.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Converters/UriConverter.cs
  examples/eventwebhook/consumer/Src/EventWebhook/EventWebhook.csproj
  examples/eventwebhook/consumer/Src/EventWebhook/Models/BounceEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/BounceEventType.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/Category.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/ClickEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/DeferredEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/DeliveredEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/DroppedEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/Event.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/EventType.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/GroupResubscribeEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/GroupUnsubscribeEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/OpenEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/Pool.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/ProcessedEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/SpamReportEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Models/UnsubscribeEvent.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Parser/EventConverter.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Parser/EventParser.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Program.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Startup.cs
  examples/eventwebhook/consumer/Src/EventWebhook/Views/EventWebhook/Index.cshtml
  examples/eventwebhook/consumer/Src/EventWebhook/appsettings.Development.json
  examples/eventwebhook/consumer/Src/EventWebhook/appsettings.json
  examples/eventwebhook/consumer/Tests/EventWebhook.Tests/EventTests.cs
  examples/eventwebhook/consumer/Tests/EventWebhook.Tests/EventWebhook.Tests.csproj
  examples/eventwebhook/consumer/Tests/EventWebhook.Tests/TestData/events.json
Labels: difficulty: very hard, hacktoberfest, status: code review request, status: hacktoberfest approved

#1032 chore: update GitHub branch references to use HEAD
  CHANGELOG.md
  CONTRIBUTING.md
  README.md
  TROUBLESHOOTING.md
  USAGE.md
  USE_CASES.md
  examples/eventwebhook/consumer/Src/EventWebhook/Views/EventWebhook/Index.cshtml
  examples/mail/mail.cs
  src/SendGrid/Helpers/Mail/README.md
  twilio_sendgrid_logo.png
Labels: status: code review request

#757 docs: Run *.md documents through Grammer.ly
  CHANGELOG.md
  CONTRIBUTING.md
  ExampleNet45ASPNetProject/README.md
  README.md
  TROUBLESHOOTING.md
  USAGE.md
  USE_CASES.md
  src/SendGrid/Helpers/Mail/README.md
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved

#789 feat: Add dockerized email inbound webhook consumer example
  examples/inbound-webhook-handler/.dockerignore
  examples/inbound-webhook-handler/.vscode/launch.json
  examples/inbound-webhook-handler/.vscode/tasks.json
  examples/inbound-webhook-handler/Dockerfile
  examples/inbound-webhook-handler/README.md
  examples/inbound-webhook-handler/SendGridInbound.sln
  examples/inbound-webhook-handler/Src/Inbound/Controllers/InboundController.cs
  examples/inbound-webhook-handler/Src/Inbound/Inbound.csproj
  examples/inbound-webhook-handler/Src/Inbound/Models/InboundEmail.cs
  examples/inbound-webhook-handler/Src/Inbound/Models/InboundEmailAddress.cs
  examples/inbound-webhook-handler/Src/Inbound/Models/InboundEmailAttachment.cs
  examples/inbound-webhook-handler/Src/Inbound/Models/InboundEmailEnvelope.cs
  examples/inbound-webhook-handler/Src/Inbound/Parsers/InboundWebhookParser.cs
  examples/inbound-webhook-handler/Src/Inbound/Program.cs
  examples/inbound-webhook-handler/Src/Inbound/Startup.cs
  examples/inbound-webhook-handler/Src/Inbound/Util/Extensions.cs
  examples/inbound-webhook-handler/Src/Inbound/Util/InboundWebhookParserHelper.cs
  examples/inbound-webhook-handler/Src/Inbound/Views/Inbound/Index.cshtml
  examples/inbound-webhook-handler/Src/Inbound/appsettings.Development.json
  examples/inbound-webhook-handler/Src/Inbound/appsettings.json
  examples/inbound-webhook-handler/Tests/Inbound.Tests/Inbound.Tests.csproj
  examples/inbound-webhook-handler/Tests/Inbound.Tests/IntegrationTests/InboundEndpointsTests.cs
  examples/inbound-webhook-handler/Tests/Inbound.Tests/Parsers/InboundWebhookParserTests.cs
  examples/inbound-webhook-handler/Tests/Inbound.Tests/sample_data/default_data.txt
  examples/inbound-webhook-handler/Tests/Inbound.Tests/sample_data/raw_data_with_attachments.txt
  examples/inbound-webhook-handler/Tests/Inbound.Tests/sample_data/raw_email_with_attachments.txt
Labels: difficulty: very hard, hacktoberfest, status: code review request, status: hacktoberfest approved

#1036 chore: simplify framework dependencies
  src/SendGrid/SendGrid.csproj
Labels: status: code review request
