Repository sendgrid/sendgrid-csharp, pull requests merged in 2020-01, with the labels that each got.

#764 docs: Update documentation for retrieving all templates
  USAGE.md
  examples/templates/templates.cs
Labels: difficulty: medium, hacktoberfest, status: code review request, status: hacktoberfest approved, type: docs update

#753 chore: Adds deploy phase that deploys to NuGet
  .travis.yml
Labels: difficulty: hard, hacktoberfest, status: code review request, status: hacktoberfest approved, type: sendgrid enhancement

#965 chore: prep the repo for automated releasing
  .travis.yml
  CHANGELOG.md
  LICENSE.txt
  Makefile
  src/SendGrid/SendGrid.csproj
Labels: status: code review request

#966 chore: deploy command needs a source URL
  .travis.yml
Labels: status: code review request

#969 chore: fix travis path for automated deploy
  .travis.yml
Labels: status: code review request

#970 chore: update travis build command
  .travis.yml
Labels: status: code review request

#971 fix: nuget push flag
  .travis.yml
Labels: status: code review request

#975 fix: update setup to allow strong naming on Travis
  .travis.yml
  Makefile
  src/SendGrid/SendGrid.csproj
  tests/SendGrid.Tests/SendGrid.Tests.csproj
Labels: status: code review request
