Repository sendgrid/sendgrid-csharp, pull requests merged in 2020-04, with the labels that each got.

#990 docs: baseline all the templated markdown docs
  .github/ISSUE_TEMPLATE
  .github/PULL_REQUEST_TEMPLATE
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  ISSUE_TEMPLATE.md
  LICENSE.md
  PULL_REQUEST_TEMPLATE.md
  README.md
  tests/SendGrid.Tests/LicenseTests.cs
  tests/SendGrid.Tests/RequiredFilesExistTest.cs
Labels: status: code review request

#903 fix: handle @ in display name when using MailHelper.StringToEmailAddress
  src/SendGrid/Helpers/Mail/MailHelper.cs
  tests/SendGrid.Tests/Integration.cs
Labels: difficulty: medium, status: code review request, type: community enhancement

#905 feat: Implement IEquatable in EmailAddress
  src/SendGrid/Helpers/Mail/Model/EmailAddress.cs
  tests/SendGrid.Tests/Helpers/Mail/EmailAddressTests.cs
Labels: status: code review request, type: community enhancement

#991 feat: ignore duplicate email addresses when serializing the message
  src/SendGrid/Helpers/Mail/Model/JsonConverters.cs
  src/SendGrid/Helpers/Mail/Model/Personalization.cs
  tests/SendGrid.Tests/Integration.cs
Labels: status: code review request

#993 fix: refactor and fix personalization inserts/updates
  src/SendGrid/Helpers/Mail/SendGridMessage.cs
Labels: status: code review request
