Repository sendgrid/sendgrid-csharp, pull requests merged in 2020-07, with the labels that each got.

#826 docs: cleanup README.md anchors and ToC
  README.md
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#824 docs: Remove references to "Whitelabel"
  USAGE.md
  USE_CASES.md
  examples/senderauthentication/senderauthentication.cs
Labels: difficulty: medium, status: code review request, status: hacktoberfest approved

#785 docs: typos fixed
  CONTRIBUTING.md
  README.md
Labels: difficulty: easy, status: code review request, status: hacktoberfest approved

#1028 chore: migrate to new default sendgrid-oai branch
  Makefile
Labels: status: code review request

#1030 feat: allow the `RetryDelegatingHandler` to be used with `HttpClientFactory`
  src/SendGrid/BaseClient.cs
  src/SendGrid/Reliability/RetryDelegatingHandler.cs
  tests/SendGrid.Tests/Integration.cs
Labels: status: code review request

#1029 fix: revert the 'SendGridClient' constructor changes
  ExampleNet45Project/Program.cs
  TROUBLESHOOTING.md
  src/SendGrid/SendGridClient.cs
  tests/SendGrid.Tests/Integration.cs
Labels: status: code review request
